side_qr = input("Введите длину стороны: ")
side = int(side_qr)
sq_qr= int(side*side)
perimetr=int(side*4)
diagonal_qr=int(2*side^2)
print("Сторона квадрата=",side,"см")
print(type(side))
print("Прощадь квадрата=",sq_qr,"см2")
print(type(side))
print("Периметр квадрата=",perimetr,"см")
print(type(perimetr))
print("Диагональ квадрата=",diagonal_qr,"см")
print(type(diagonal_qr))

